### ISSUE TITLE
force-tcp not work.

### ISSUE THREAD

**Issue by smaller09** [tun2proxy/dns2socks#1]
I'm running dns2socks on an openwrt router.  and I want dns2socks only use tcp to connect to upstream server.

`dns2socks-rust --listen-addr 127.0.0.1:5300 --force-tcp --cache-records`

dns2socks works as expect.  can resolve hostname through socks5 proxy.

but I still got this in system log.

`daemon.err dns2socks-rust[5023]: [2024-04-30T16:54:56Z ERROR dns2socks] DNS query via UDP incoming handler error "querying "github-cloud.s3.amazonaws.com." timed out"`

**Comment by ssrlive** [comment]
This is unimportant. Any DNS query has the possibility of timeout and failure.
You can append a parameter `-v trace` after your command line, so that you can see the log output after each successful query.

**Comment by ssrlive** [comment]
Fixed in deb78747149cf04a34b02843771989229b631654 . Sorry for delay.
